import type { BrandInvoice } from '@/services/payments.service';

export interface InvoiceBrandDetails {
  companyName: string;
  city?: string;
  contactEmail?: string;
}

export function printInvoice(
  invoice: BrandInvoice & { lineItems?: { description: string; amount: number }[] },
  brand: InvoiceBrandDetails,
): void {
  const statusLabel =
    invoice.status === 'paid' ? 'PAID' :
    invoice.status === 'overdue' ? 'OVERDUE' : 'DUE';
  const statusColor =
    invoice.status === 'paid' ? '#185c39' :
    invoice.status === 'overdue' ? '#c13a3a' : '#8b5e12';
  const statusBg =
    invoice.status === 'paid' ? '#e7f0ea' :
    invoice.status === 'overdue' ? '#fce4e4' : '#fff1cd';

  const lines = (
    invoice.lineItems ?? [
      { description: `Creator services — ${invoice.periodLabel}`, amount: invoice.amount },
    ]
  )
    .map(
      (item) =>
        `<tr>
          <td style="padding:8px 0;font-size:13px;color:#3a5244;border-bottom:1px solid #f0f4f2;">${item.description}</td>
          <td style="padding:8px 0;font-size:13px;font-weight:700;text-align:right;color:#173b2a;border-bottom:1px solid #f0f4f2;">Rs&nbsp;${item.amount.toLocaleString()}</td>
        </tr>`,
    )
    .join('');

  const fmtDate = (iso: string) =>
    new Date(iso).toLocaleDateString('en-PK', {
      timeZone: 'Asia/Karachi',
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Invoice #${invoice.id.slice(0, 8).toUpperCase()}</title>
<style>
  @page{margin:2cm}
  *{box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#173b2a;background:#fff;margin:0;padding:32px}
  .hd{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:24px;border-bottom:2px solid #e6eceb;margin-bottom:28px}
  .logo{font-size:22px;font-weight:900;color:#185c39;letter-spacing:-0.05em}
  .sub{font-size:11px;font-weight:700;color:#9ba8a1;text-transform:uppercase;letter-spacing:0.12em;margin-top:3px}
  .inv{font-size:28px;font-weight:900;letter-spacing:-0.04em;text-align:right}
  .inv-id{font-family:monospace;font-size:12px;color:#9ba8a1;text-align:right;margin-top:4px}
  .badge{display:inline-block;padding:4px 12px;border-radius:100px;font-size:11px;font-weight:900;letter-spacing:0.1em;margin-top:8px;color:${statusColor};background:${statusBg}}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-bottom:28px}
  .lbl{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.14em;color:#9ba8a1;margin-bottom:4px}
  .val{font-size:14px;font-weight:700;color:#173b2a}
  .sub-val{font-size:13px;color:#647168;margin-top:2px}
  table{width:100%;border-collapse:collapse}
  thead th{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.14em;color:#9ba8a1;padding:0 0 10px;border-bottom:2px solid #e6eceb;text-align:left}
  thead th:last-child{text-align:right}
  .total td{padding-top:14px;font-size:15px;font-weight:900;color:#173b2a}
  .total td:last-child{text-align:right;font-size:18px}
  footer{margin-top:40px;padding-top:16px;border-top:1px solid #e6eceb;font-size:11px;color:#9ba8a1;text-align:center}
  @media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style>
</head>
<body>
<div class="hd">
  <div>
    <div class="logo">ZingZing</div>
    <div class="sub">Creator Marketing Platform</div>
    <div class="sub-val" style="margin-top:10px">support@zingzing.pk</div>
  </div>
  <div>
    <div class="inv">Invoice</div>
    <div class="inv-id">#${invoice.id.slice(0, 8).toUpperCase()}</div>
    <div style="text-align:right"><span class="badge">${statusLabel}</span></div>
  </div>
</div>
<div class="grid">
  <div>
    <div class="lbl">Billed to</div>
    <div class="val">${brand.companyName}</div>
    ${brand.city ? `<div class="sub-val">${brand.city}</div>` : ''}
    ${brand.contactEmail ? `<div class="sub-val">${brand.contactEmail}</div>` : ''}
  </div>
  <div>
    <div class="lbl">Period</div>
    <div class="val">${invoice.periodLabel}</div>
    <div style="margin-top:12px"><div class="lbl">Issued</div><div class="val">${fmtDate(invoice.issuedAt)}</div></div>
    <div style="margin-top:12px"><div class="lbl">Due</div><div class="val">${fmtDate(invoice.dueAt)}</div></div>
  </div>
</div>
<table>
  <thead><tr><th>Description</th><th style="text-align:right">Amount</th></tr></thead>
  <tbody>
    ${lines}
    <tr class="total"><td>Total</td><td>Rs&nbsp;${invoice.amount.toLocaleString()}</td></tr>
  </tbody>
</table>
<footer>Generated by ZingZing &middot; Computer-generated document &middot; Retain for your records.</footer>
</body>
</html>`;

  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) { return; }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => { win.print(); }, 400);
}
