export const MARKET_CONFIG = {
  countryName: 'Pakistan',
  countryCode: 'PK',
  locale: 'en-PK',
  currency: 'PKR',
  currencySymbol: 'Rs',
  timezone: 'Asia/Karachi',
  phoneCountryCode: '+92',
} as const;

export const pakistanCities = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Hyderabad',
  'Gujranwala',
  'Sialkot',
  'Sargodha',
  'Bahawalpur',
  'Sukkur',
  'Larkana',
  'Mardan',
  'Abbottabad',
  'Swat',
  'Gujrat',
  'Kasur',
  'Rahim Yar Khan',
  'Sahiwal',
  'Okara',
  'Wah Cantt',
] as const;

export const pakistanLanguages = [
  'Urdu',
  'Punjabi',
  'Sindhi',
  'Pashto',
  'Balochi',
  'Saraiki',
  'Hindko',
  'Brahui',
  'English',
] as const;
