export const MARKET_CONFIG = {
  countryName: 'Pakistan',
  countryCode: 'PK',
  locale: 'en-PK',
  currency: 'PKR',
  currencySymbol: 'Rs',
  timezone: 'Asia/Karachi',
  phoneCountryCode: '+92',
} as const;

export const pakistanCities = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Hyderabad',
  'Gujranwala',
  'Sialkot',
  'Sargodha',
  'Bahawalpur',
  'Sukkur',
  'Larkana',
  'Mardan',
  'Abbottabad',
  'Haripur',
  'Swat',
  'Gujrat',
  'Kasur',
  'Rahim Yar Khan',
  'Sahiwal',
  'Okara',
  'Wah Cantt',
] as const;

export const pakistanRegions = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa',
  'Balochistan',
  'Islamabad Capital Territory',
  'Azad Jammu and Kashmir',
  'Gilgit-Baltistan',
] as const;

export const cityToRegionMap: Partial<Record<(typeof pakistanCities)[number], (typeof pakistanRegions)[number]>> = {
  Karachi: 'Sindh',
  Hyderabad: 'Sindh',
  Sukkur: 'Sindh',
  Larkana: 'Sindh',
  Lahore: 'Punjab',
  Rawalpindi: 'Punjab',
  Faisalabad: 'Punjab',
  Multan: 'Punjab',
  Gujranwala: 'Punjab',
  Sialkot: 'Punjab',
  Sargodha: 'Punjab',
  Bahawalpur: 'Punjab',
  Gujrat: 'Punjab',
  Kasur: 'Punjab',
  'Rahim Yar Khan': 'Punjab',
  Sahiwal: 'Punjab',
  Okara: 'Punjab',
  'Wah Cantt': 'Punjab',
  Islamabad: 'Islamabad Capital Territory',
  Peshawar: 'Khyber Pakhtunkhwa',
  Mardan: 'Khyber Pakhtunkhwa',
  Abbottabad: 'Khyber Pakhtunkhwa',
  Haripur: 'Khyber Pakhtunkhwa',
  Swat: 'Khyber Pakhtunkhwa',
  Quetta: 'Balochistan',
};

export const pakistanLanguages = [
  'Urdu',
  'Punjabi',
  'Sindhi',
  'Pashto',
  'Balochi',
  'Saraiki',
  'Hindko',
  'Brahui',
  'English',
] as const;
