const pakistanCities = [
  "Abbottabad",
  "Ahmedpur East",
  "Attock",
  "Bahawalnagar",
  "Bahawalpur",
  "Bannu",
  "Batkhela",
  "Bhakkar",
  "Bhalwal",
  "Burewala",
  "Chakwal",
  "Charsadda",
  "Chiniot",
  "Dadu",
  "Daska",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Ghotki",
  "Gujranwala",
  "Gujrat",
  "Hafizabad",
  "Haripur",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Kamoke",
  "Karachi",
  "Kasur",
  "Khairpur",
  "Khanewal",
  "Khuzdar",
  "Kohat",
  "Kotli",
  "Lahore",
  "Larkana",
  "Mandi Bahauddin",
  "Mansehra",
  "Mardan",
  "Mirpur",
  "Mirpur Khas",
  "Multan",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nawabshah",
  "Nowshera",
  "Okara",
  "Pakpattan",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sadiqabad",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Shikarpur",
  "Sialkot",
  "Sukkur",
  "Swabi",
  "Swat",
  "Tando Adam",
  "Turbat",
  "Vehari",
  "Wah Cantonment",
  "Wazirabad"
];

export default pakistanCities;
