const defaultCategoryImage = "/media/hero.png";

export const cards = [
  { id: 1, title: "Comedy & Entertainment", desc: "Make audiences laugh and stay engaged", img: defaultCategoryImage, slug: "comedy" },
  { id: 2, title: "Food & Restaurant Reviews", desc: "Showcase dining spots and culinary experiences", img: defaultCategoryImage, slug: "food" },
  { id: 3, title: "Fashion", desc: "Promote outfits, styling, and personal brand looks", img: defaultCategoryImage, slug: "fashion" },
  { id: 4, title: "Beauty & Makeup", desc: "Highlight beauty routines, skincare, and glam content", img: defaultCategoryImage, slug: "beauty" },
  { id: 5, title: "Fitness & Health", desc: "Create wellness-driven collaborations that inspire action", img: defaultCategoryImage, slug: "fitness" },
  { id: 6, title: "Lifestyle & Daily Vlogs", desc: "Tell relatable everyday stories that connect with viewers", img: defaultCategoryImage, slug: "lifestyle" },
  { id: 7, title: "Tech & Gadgets", desc: "Feature the latest devices, tools, and digital experiences", img: defaultCategoryImage, slug: "tech" },
  { id: 8, title: "Education / Edutainment", desc: "Turn learning moments into engaging creator content", img: defaultCategoryImage, slug: "education" },
  { id: 9, title: "Travel & Tourism", desc: "Promote destinations, stays, and memorable trips", img: defaultCategoryImage, slug: "travel" },
  { id: 10, title: "Couples & Relationships", desc: "Create content around shared moments and connection", img: defaultCategoryImage, slug: "couples" },
  { id: 11, title: "Family & Parenting", desc: "Reach family-first audiences with trust-led stories", img: defaultCategoryImage, slug: "family" },
  { id: 12, title: "Music & Singing", desc: "Collaborate with performers, vocalists, and music creators", img: defaultCategoryImage, slug: "music" },
  { id: 13, title: "Islamic & Cultural", desc: "Share faith-aware and culturally rooted campaigns", img: defaultCategoryImage, slug: "islamic" },
  { id: 14, title: "Gaming", desc: "Activate gaming communities with high-engagement content", img: defaultCategoryImage, slug: "gaming" },
  { id: 15, title: "Product Reviews & Unboxing", desc: "Drive purchase intent with trusted first impressions", img: defaultCategoryImage, slug: "reviews" },
  { id: 16, title: "Business & Entrepreneurship", desc: "Reach ambitious founders, operators, and professionals", img: defaultCategoryImage, slug: "business" },
  { id: 17, title: "Finance & Investing", desc: "Connect with audiences focused on money and growth", img: defaultCategoryImage, slug: "finance" },
  { id: 18, title: "Motivation & Self Development", desc: "Inspire action through mindset and personal growth content", img: defaultCategoryImage, slug: "motivation" },
  { id: 19, title: "News & Current Affairs", desc: "Amplify timely, relevant commentary and updates", img: defaultCategoryImage, slug: "news" },
  { id: 20, title: "Automobile & Cars", desc: "Showcase vehicles, accessories, and automotive lifestyle", img: defaultCategoryImage, slug: "automobile" },
];

  export const projects = [
    {
      id: 1,
          img: "https://images.pexels.com/photos/6896221/pexels-photo-6896221.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Comedy & Entertainment",
          username: "Areeba Khan",
    },
    {
      id: 2,
          img: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/3775534/pexels-photo-3775534.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Food & Restaurant Reviews",
          username: "Chef Hamza",
    },
    {
      id: 3,
          img: "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Fashion",
          username: "Zoya Ali",
    },
    {
      id: 4,
          img: "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Beauty & Makeup",
          username: "Minal Studio",
    },
    {
      id: 5,
          img: "https://images.pexels.com/photos/6550851/pexels-photo-6550851.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Fitness & Health",
          username: "Coach Salman",
    },
    {
      id: 6,
          img: "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Travel & Tourism",
          username: "Taimoor Travels",
    },
    {
      id: 7,
          img: "https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Tech & Gadgets",
          username: "Bilal Tech Reviews",
    },
    {
      id: 8,
          img: "https://images.pexels.com/photos/9072216/pexels-photo-9072216.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/3771839/pexels-photo-3771839.jpeg?auto=compress&cs=tinysrgb&w=1600",
          cat: "Product Reviews & Unboxing",
          username: "Hira Unboxes",
    },
  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai art character from your images and prompts",
      price: 59,
      star: 5,
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ultra high quality character art with ai",
      price: 79,
      star: 5,
      username: "Lannie Coleman",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will creating unique ai generated artworks mid journey ai artist",
      price: 112,
      star: 5,
      username: "Carol Steve",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 99,
      star: 4,
      username: "Don Weber",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will recreate your dreams in high quality pictures",
      price: 59,
      star: 5,
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 79,
      star: 4,
      username: "Walton Shepard ",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate images with your prompts using ai dalle",
      price: 89,
      star: 5,
      username: "Waverly Schaefer",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom art using midjourney generator",
      price: 110,
      star: 4,
      username: "Wilton Hunt",
    },
  ];
  